name: Deploy Nodejs Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t abegunde99/football_previews .  
      - name: Publish image to docker hub
        run: docker push abegunde99/football_previews:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull abegunde99/football_previews:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container 
      - name: Run docker container
        run: docker run -d -p 80:80 --name nodejs-app-container abegunde99/football_previews